[common]
# Port for frpc to connect to
bind_port = 7000
# Port for mapping http challenges (match docker-compose ports)
vhost_http_port = 8001
token = your_whale_token
# Set to your domain or use 127.0.0.1.nip.io for local dev
subdomain_host = 127.0.0.1.nip.io
